// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice =
  | GetInTouchSlice
  | BbbAccreditedSlice
  | HomepageBeforeAndAfterSlice
  | OurServicesSlice
  | HomePageContactFormSlice
  | TwoImagesWithCtaOnRightSlice;

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Page Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ContactPageContactFormSlice
  | ContactPhoneAndEmailSlice
  | GetInTouchSlice
  | ServiceSlice
  | ServicesSecondHeaderSlice
  | GeneralPageHeaderSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → General Navigation*
 */
export interface SettingsDocumentDataGeneralNavigationItem {
  /**
   * link field in *Settings → General Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.general_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *Settings → General Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.general_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → Footer Navigation*
 */
export interface SettingsDocumentDataFooterNavigationItem {
  /**
   * Footer Nav Label field in *Settings → Footer Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].footer_nav_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_nav_label: prismic.KeyTextField;

  /**
   * Footer Nav Link field in *Settings → Footer Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[].footer_nav_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  footer_nav_link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site TItle Appended field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never> /**
   * General Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.general_navigation[]
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  general_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataGeneralNavigationItem>
  >;

  /**
   * CTA Label field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_label
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta_link
   * - **Tab**: Navigation
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField /**
   * Paragraph On Left field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.paragraph_on_left
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  paragraph_on_left: prismic.RichTextField;

  /**
   * Footer Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavigationItem>
  >;

  /**
   * Get In Touch Header field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.get_in_touch_header
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  get_in_touch_header: prismic.KeyTextField;

  /**
   * Get In Touch Paragraph field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.get_in_touch_paragraph
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  get_in_touch_paragraph: prismic.RichTextField /**
   * Dev Contact Email Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.dev_contact_email_address
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  dev_contact_email_address: prismic.KeyTextField;

  /**
   * Contact Email Address field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_email_address
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_email_address: prismic.KeyTextField;

  /**
   * Contact Phone Number field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_phone_number
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_phone_number: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomePageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *BbbAccredited → Primary*
 */
export interface BbbAccreditedSliceDefaultPrimary {
  /**
   * Paragraph field in *BbbAccredited → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bbb_accredited.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for BbbAccredited Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BbbAccreditedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BbbAccreditedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BbbAccredited*
 */
type BbbAccreditedSliceVariation = BbbAccreditedSliceDefault;

/**
 * BbbAccredited Shared Slice
 *
 * - **API ID**: `bbb_accredited`
 * - **Description**: BbbAccredited
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BbbAccreditedSlice = prismic.SharedSlice<
  "bbb_accredited",
  BbbAccreditedSliceVariation
>;

/**
 * Primary content in *ContactPageContactForm → Primary*
 */
export interface ContactPageContactFormSliceDefaultPrimary {
  /**
   * Header h2 field in *ContactPageContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page_contact_form.primary.header_h2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h2: prismic.KeyTextField;

  /**
   * Header h3 black text field in *ContactPageContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page_contact_form.primary.header_h3_black_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h3_black_text: prismic.KeyTextField;

  /**
   * Header h3 gold text field in *ContactPageContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page_contact_form.primary.header_h3_gold_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h3_gold_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactPageContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactPageContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactPageContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactPageContactForm*
 */
type ContactPageContactFormSliceVariation = ContactPageContactFormSliceDefault;

/**
 * ContactPageContactForm Shared Slice
 *
 * - **API ID**: `contact_page_contact_form`
 * - **Description**: ContactPageContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactPageContactFormSlice = prismic.SharedSlice<
  "contact_page_contact_form",
  ContactPageContactFormSliceVariation
>;

/**
 * Primary content in *ContactPhoneAndEmail → Primary*
 */
export interface ContactPhoneAndEmailSliceDefaultPrimary {
  /**
   * Header h2 field in *ContactPhoneAndEmail → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_phone_and_email.primary.header_h2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h2: prismic.KeyTextField;

  /**
   * Phone Text field in *ContactPhoneAndEmail → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_phone_and_email.primary.phone_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_text: prismic.KeyTextField;

  /**
   * Email Text field in *ContactPhoneAndEmail → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_phone_and_email.primary.email_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_text: prismic.KeyTextField;
}

/**
 * Default variation for ContactPhoneAndEmail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactPhoneAndEmailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactPhoneAndEmailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactPhoneAndEmail*
 */
type ContactPhoneAndEmailSliceVariation = ContactPhoneAndEmailSliceDefault;

/**
 * ContactPhoneAndEmail Shared Slice
 *
 * - **API ID**: `contact_phone_and_email`
 * - **Description**: ContactPhoneAndEmail
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactPhoneAndEmailSlice = prismic.SharedSlice<
  "contact_phone_and_email",
  ContactPhoneAndEmailSliceVariation
>;

/**
 * Primary content in *GeneralPageHeader → Primary*
 */
export interface GeneralPageHeaderSliceDefaultPrimary {
  /**
   * Header Text field in *GeneralPageHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_page_header.primary.header_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_text: prismic.KeyTextField;

  /**
   * Breadcrumb Text field in *GeneralPageHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: general_page_header.primary.breadcrumb_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  breadcrumb_text: prismic.KeyTextField;

  /**
   * Background Desktop field in *GeneralPageHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general_page_header.primary.background_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_desktop: prismic.ImageField<never>;

  /**
   * Background Mobile field in *GeneralPageHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: general_page_header.primary.background_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_mobile: prismic.ImageField<never>;
}

/**
 * Default variation for GeneralPageHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GeneralPageHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GeneralPageHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GeneralPageHeader*
 */
type GeneralPageHeaderSliceVariation = GeneralPageHeaderSliceDefault;

/**
 * GeneralPageHeader Shared Slice
 *
 * - **API ID**: `general_page_header`
 * - **Description**: GeneralPageHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GeneralPageHeaderSlice = prismic.SharedSlice<
  "general_page_header",
  GeneralPageHeaderSliceVariation
>;

/**
 * Primary content in *GetInTouch → Primary*
 */
export interface GetInTouchSliceDefaultPrimary {
  /**
   * Paragraph field in *GetInTouch → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: get_in_touch.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for GetInTouch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetInTouchSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GetInTouchSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GetInTouch*
 */
type GetInTouchSliceVariation = GetInTouchSliceDefault;

/**
 * GetInTouch Shared Slice
 *
 * - **API ID**: `get_in_touch`
 * - **Description**: GetInTouch
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GetInTouchSlice = prismic.SharedSlice<
  "get_in_touch",
  GetInTouchSliceVariation
>;

/**
 * Primary content in *HomePageContactForm → Primary*
 */
export interface HomePageContactFormSliceDefaultPrimary {
  /**
   * Background Image field in *HomePageContactForm → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_contact_form.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * First Heading field in *HomePageContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_contact_form.primary.first_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_heading: prismic.KeyTextField;

  /**
   * Second Heading field in *HomePageContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_contact_form.primary.second_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_heading: prismic.KeyTextField;

  /**
   * Paragraph field in *HomePageContactForm → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page_contact_form.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for HomePageContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomePageContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomePageContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomePageContactForm*
 */
type HomePageContactFormSliceVariation = HomePageContactFormSliceDefault;

/**
 * HomePageContactForm Shared Slice
 *
 * - **API ID**: `home_page_contact_form`
 * - **Description**: HomePageContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomePageContactFormSlice = prismic.SharedSlice<
  "home_page_contact_form",
  HomePageContactFormSliceVariation
>;

/**
 * Primary content in *HomepageBeforeAndAfter → Primary*
 */
export interface HomepageBeforeAndAfterSliceDefaultPrimary {
  /**
   * Header field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Description field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * CTA Text field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Image 1 field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *HomepageBeforeAndAfter → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_before_and_after.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;
}

/**
 * Default variation for HomepageBeforeAndAfter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageBeforeAndAfterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomepageBeforeAndAfterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomepageBeforeAndAfter*
 */
type HomepageBeforeAndAfterSliceVariation = HomepageBeforeAndAfterSliceDefault;

/**
 * HomepageBeforeAndAfter Shared Slice
 *
 * - **API ID**: `homepage_before_and_after`
 * - **Description**: HomepageBeforeAndAfter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageBeforeAndAfterSlice = prismic.SharedSlice<
  "homepage_before_and_after",
  HomepageBeforeAndAfterSliceVariation
>;

/**
 * Primary content in *OurServices → Primary*
 */
export interface OurServicesSliceDefaultPrimary {
  /**
   * First Header field in *OurServices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.first_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_header: prismic.KeyTextField;

  /**
   * Second Header 1st Black Text field in *OurServices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.second_header_1st_black_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_header_1st_black_text: prismic.KeyTextField;

  /**
   * Second Header Gold Text field in *OurServices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.second_header_gold_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_header_gold_text: prismic.KeyTextField;

  /**
   * Second Header 2nd Black Text field in *OurServices → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.primary.second_header_2nd_black_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_header_2nd_black_text: prismic.KeyTextField;
}

/**
 * Primary content in *OurServices → Items*
 */
export interface OurServicesSliceDefaultItem {
  /**
   * Service Image field in *OurServices → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Service Header field in *OurServices → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].service_header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_header: prismic.KeyTextField;

  /**
   * Service Description field in *OurServices → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_services.items[].service_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_description: prismic.KeyTextField;
}

/**
 * Default variation for OurServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurServicesSliceDefaultPrimary>,
  Simplify<OurServicesSliceDefaultItem>
>;

/**
 * Slice variation for *OurServices*
 */
type OurServicesSliceVariation = OurServicesSliceDefault;

/**
 * OurServices Shared Slice
 *
 * - **API ID**: `our_services`
 * - **Description**: OurServices
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurServicesSlice = prismic.SharedSlice<
  "our_services",
  OurServicesSliceVariation
>;

/**
 * Primary content in *Service → Primary*
 */
export interface ServiceSliceDefaultPrimary {
  /**
   * Header h2 field in *Service → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.header_h2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h2: prismic.KeyTextField;

  /**
   * Header h3 field in *Service → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.header_h3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h3: prismic.KeyTextField;

  /**
   * Paragraph field in *Service → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Header h4 field in *Service → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.header_h4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_h4: prismic.KeyTextField;

  /**
   * Image 1 field in *Service → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Service → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Image 3 field in *Service → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_3: prismic.ImageField<never>;

  /**
   * Image 4 field in *Service → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.primary.image_4
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_4: prismic.ImageField<never>;
}

/**
 * Primary content in *Service → Items*
 */
export interface ServiceSliceDefaultItem {
  /**
   * Service field in *Service → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.items[].service
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service: prismic.KeyTextField;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSliceDefaultPrimary>,
  Simplify<ServiceSliceDefaultItem>
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  "service",
  ServiceSliceVariation
>;

/**
 * Primary content in *ServicesSecondHeader → Primary*
 */
export interface ServicesSecondHeaderSliceDefaultPrimary {
  /**
   * Header field in *ServicesSecondHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_second_header.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Header Gold Text field in *ServicesSecondHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_second_header.primary.header_gold_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header_gold_text: prismic.KeyTextField;

  /**
   * Paragraph field in *ServicesSecondHeader → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_second_header.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Image On Left field in *ServicesSecondHeader → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_second_header.primary.image_on_left
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_on_left: prismic.ImageField<never>;
}

/**
 * Default variation for ServicesSecondHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSecondHeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSecondHeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSecondHeader*
 */
type ServicesSecondHeaderSliceVariation = ServicesSecondHeaderSliceDefault;

/**
 * ServicesSecondHeader Shared Slice
 *
 * - **API ID**: `services_second_header`
 * - **Description**: ServicesSecondHeader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSecondHeaderSlice = prismic.SharedSlice<
  "services_second_header",
  ServicesSecondHeaderSliceVariation
>;

/**
 * Primary content in *TwoImagesWithCtaOnRight → Primary*
 */
export interface TwoImagesWithCtaOnRightSliceDefaultPrimary {
  /**
   * Image 1 field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * First Header field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.first_header
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_header: prismic.TitleField;

  /**
   * Second Header Black Text field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.second_header_black_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_header_black_text: prismic.KeyTextField;

  /**
   * Second Header Gold Text field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.second_header_gold_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_header_gold_text: prismic.KeyTextField;

  /**
   * Paragraph field in *TwoImagesWithCtaOnRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_images_with_cta_on_right.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for TwoImagesWithCtaOnRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoImagesWithCtaOnRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoImagesWithCtaOnRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TwoImagesWithCtaOnRight*
 */
type TwoImagesWithCtaOnRightSliceVariation =
  TwoImagesWithCtaOnRightSliceDefault;

/**
 * TwoImagesWithCtaOnRight Shared Slice
 *
 * - **API ID**: `two_images_with_cta_on_right`
 * - **Description**: TwoImagesWithCtaOnRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoImagesWithCtaOnRightSlice = prismic.SharedSlice<
  "two_images_with_cta_on_right",
  TwoImagesWithCtaOnRightSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataGeneralNavigationItem,
      SettingsDocumentDataFooterNavigationItem,
      AllDocumentTypes,
      BbbAccreditedSlice,
      BbbAccreditedSliceDefaultPrimary,
      BbbAccreditedSliceVariation,
      BbbAccreditedSliceDefault,
      ContactPageContactFormSlice,
      ContactPageContactFormSliceDefaultPrimary,
      ContactPageContactFormSliceVariation,
      ContactPageContactFormSliceDefault,
      ContactPhoneAndEmailSlice,
      ContactPhoneAndEmailSliceDefaultPrimary,
      ContactPhoneAndEmailSliceVariation,
      ContactPhoneAndEmailSliceDefault,
      GeneralPageHeaderSlice,
      GeneralPageHeaderSliceDefaultPrimary,
      GeneralPageHeaderSliceVariation,
      GeneralPageHeaderSliceDefault,
      GetInTouchSlice,
      GetInTouchSliceDefaultPrimary,
      GetInTouchSliceVariation,
      GetInTouchSliceDefault,
      HomePageContactFormSlice,
      HomePageContactFormSliceDefaultPrimary,
      HomePageContactFormSliceVariation,
      HomePageContactFormSliceDefault,
      HomepageBeforeAndAfterSlice,
      HomepageBeforeAndAfterSliceDefaultPrimary,
      HomepageBeforeAndAfterSliceVariation,
      HomepageBeforeAndAfterSliceDefault,
      OurServicesSlice,
      OurServicesSliceDefaultPrimary,
      OurServicesSliceDefaultItem,
      OurServicesSliceVariation,
      OurServicesSliceDefault,
      ServiceSlice,
      ServiceSliceDefaultPrimary,
      ServiceSliceDefaultItem,
      ServiceSliceVariation,
      ServiceSliceDefault,
      ServicesSecondHeaderSlice,
      ServicesSecondHeaderSliceDefaultPrimary,
      ServicesSecondHeaderSliceVariation,
      ServicesSecondHeaderSliceDefault,
      TwoImagesWithCtaOnRightSlice,
      TwoImagesWithCtaOnRightSliceDefaultPrimary,
      TwoImagesWithCtaOnRightSliceVariation,
      TwoImagesWithCtaOnRightSliceDefault,
    };
  }
}
