// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bbb_accredited: dynamic(() => import("./BbbAccredited")),
  before_and_after_carousel: dynamic(() => import("./BeforeAndAfterCarousel")),
  contact_page_contact_form: dynamic(() => import("./ContactPageContactForm")),
  contact_phone_and_email: dynamic(() => import("./ContactPhoneAndEmail")),
  general_page_header: dynamic(() => import("./GeneralPageHeader")),
  get_in_touch: dynamic(() => import("./GetInTouch")),
  home_page_contact_form: dynamic(() => import("./HomePageContactForm")),
  homepage_before_and_after: dynamic(() => import("./HomepageBeforeAndAfter")),
  our_services: dynamic(() => import("./OurServices")),
  service: dynamic(() => import("./Service")),
  services_second_header: dynamic(() => import("./ServicesSecondHeader")),
  two_images_with_cta_on_right: dynamic(
    () => import("./TwoImagesWithCtaOnRight"),
  ),
};
